### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by sundyCoder** [Guildenstern/Tartini#4]
In file included from widgets/freq/freqwidgetGL.cpp:38:0:
general/mygl.h: In function ‘void mygl_resize2d(int, int)’:
general/mygl.h:45:24: error: ‘gluOrtho2D’ was not declared in this scope
   gluOrtho2D(0, w, h, 0);
                        ^
make: **\* [.obj/freqwidgetGL.o] Error 1

**Comment by quicky2000** [comment]
Hi SundyCoder,

Please refer to my repo https://github.com/quicky2000/tartini-debian.
I forked https://github.com/jeremysalwen/tartini-debian and apply all past debian-patches ( including code cleaning) on the code so that it is usable without using debian packaging tools
Normally the latest version doesn't have this issue. I succeeded to compile on Kubuntu 14.04
My next step is to integrate Guildenstern modifications ( translations and Travis files ) so that a single repo contains all patches

**Comment by quicky2000** [comment]
Hi SundyCoder,

I realised it was not a good idea to for tartini-debian repo as its purpose is to package tartini for debian.
It is cleaner to create a new repo from the official release and integrate patches

I succeed to make tarvis works in my own repository:
https://github.com/quicky2000/tartini
You can see the build status here :
https://travis-ci.org/quicky2000/tartini/

For information I created this repo from the official release of Tartini and I integrated all debian patches coming from https://github.com/jeremysalwen/tartini-debian
These patches contain same kind of patch performed by various people to compile but there are also some corrections in memory management. some issues that are solved etc.
I also integrated Guildenstern internationalisation work in master branch and integrate the porting of Qwt6 in a separated branch ( not pushed in my repo at this time due to compilation issues)

Normally according to my research about Tartini I think I have integrated all patches that have been published. The aim is to have a consistent repo to make Tartini evolve.

I will try to continue to work on the code, suggestions are welcomed

**Comment by sundyCoder** [comment]
Thank you very much! I have already solved this issue.

**Comment by quicky2000** [comment]
Ok, for your information I`m working on Qwt6 migration
